### ISSUE TITLE
Demo please

### ISSUE THREAD

**Issue by onigetoc** [ChoiZ/php-playlist-generator#1]
Can you do a simple demo file to learn how it work?

I want to use a form, post it and create a m3u file or text file.

I do not want to download it but to write a file and to add the new station to the existing file from a form.

Thank you

**Comment by ChoiZ** [comment]
You can test with PHP CLI like: 
```$ php generate.php```

With a form you can modify generate php like that:
```
<?php
require 'station.php';
require 'playlist.php';
$station = new Station($_POST['filename'], $_POST['description'], $_POST['url']);
$station->addServer($_POST['server1']);
$station->addServer($_POST['server2']);
$station->addServer($_POST['server3']);
$playlist = new Playlist($station, 'm3u');
$playlist->generate();
```

Example form:
```
<form method="post" action="generate.php">
<label>Filename:<input type="text" name="filename"></label>
<label>Description:<input type="text" name="description"></label>
<label>Url (https://www.yourwebsite.com):<input type="text" name="url"></label>
<label>Server 1:<input type="text" name="server1"></label>
<label>Server 2:<input type="text" name="server2"></label>
<label>Server 3:<input type="text" name="server3"></label>
<input type="submit">
</form>
```

**Comment by onigetoc** [comment]
Hi, How to stop file downloading? i want to write a file or to add to database and no file download.

Thank you

**Comment by ChoiZ** [comment]
Remove or comment the 4th lines below:
https://github.com/ChoiZ/php-playlist-generator/blob/master/playlist.php#L59
